### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by WOLD-STUBBY**
DIS IS STUBS THINGS

### CODE REVIEW

**Comment by hanlunli** [comment]
you need to open the branch

**Comment by hanlunli** [comment]
also, this isn't the the of branch that we have, (me, Albert,Baron,Claire)because we did al lot of terminal coding and things.

**Comment by hanlunli** [comment]
NVM

**Comment by hanlunli** [comment]
don't open

**Comment by WOLD-STUBBY** [comment]
send link

**Comment by shawnli2020** [comment]
Merge in Austin's homework_1 slide deck

**Pull request merged**
